# Generated by Django 2.2.5 on 2020-03-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=128)),
                ('amount', models.FloatField(default=0)),
                ('currency', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='fx_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eur_to_gbp', models.FloatField(default=0)),
                ('aud_to_gbp', models.FloatField(default=0)),
                ('usd_to_gbp', models.FloatField(default=0)),
                ('date_time', models.CharField(default='', max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ticker', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('quantity', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('currency', models.CharField(max_length=128)),
            ],
        ),
    ]
