# Generated by Django 2.2.5 on 2020-04-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx_rates_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
