# Generated by Django 2.2.5 on 2020-04-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx_rates_app', '0002_cash_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='total',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
