# Generated by Django 2.2.5 on 2020-04-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fx_rates_app', '0003_auto_20200402_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='total',
        ),
    ]
