# Generated by Django 3.0.3 on 2020-04-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx_rates_app', '0005_shares_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='current_price',
            field=models.FloatField(null=True),
        ),
    ]
