# Generated by Django 3.0.3 on 2020-04-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx_rates_app', '0006_auto_20200428_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shares',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='shares',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='shares',
            name='date',
        ),
        migrations.RemoveField(
            model_name='shares',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shares',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='shares',
            name='ticker',
        ),
        migrations.AlterField(
            model_name='shares',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
