# Generated by Django 3.0.3 on 2020-04-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx_rates_app', '0007_auto_20200428_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='currency',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='shares',
            name='current_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='shares',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='shares',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='shares',
            name='quantity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='shares',
            name='ticker',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
