# Generated by Django 3.0.3 on 2020-07-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fx_rates_app', '0008_auto_20200428_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fx_table',
            name='date_time',
            field=models.DateTimeField(default='', max_length=264, unique=True),
        ),
    ]
